### PR TITLE
Add upgrade-current-box step to the migrate-to-new-box instructions 

### PR DESCRIPTION
**Pull request by nordurljosahvida**
The transition will fail if the current box is not at the latest version of MIAB. All users should upgrade the current box before proceeding onto the new one.

### CODE REVIEW

**Comment by anoma** [comment]
For consideration. Given that `latest` is an arbitrary tag does it not make more sense to build the new box at the same version as the old box even if that happens to be older. 

This would derisk having a last minute upgrade issues or coincidentally finding  MIAB release day bugs during a potentially prebooked finite outage window.

**Comment by nikksno** [comment]
That's a valid point but MIAB updates are so far apart it would be very unlikely for one to happen in between, but yes it could happen. That said, do you think setting up a new box with an old version is better than forcing the user to [potentially] having to upgrade twice in the remote event an update happens exactly during the migration?

**Comment by anoma** [comment]
Yeah I am not sure what the right answer is but I can say from personal experience I have hit one of the "rare" upgrade problems the day I had booked to move mail server.

If we were looking for a sensible compromise perhaps we can suggest that the preparation of the new server be done in advance of the day of migration.

To be clear though this PR is still better than we have this now so this is all for discussion only.

**Comment by nikksno** [comment]
Ok, I agree there could be an even better way to do this, that could be a solution but maybe too complex for the user? @JoshData any ideas?

**Comment by JoshData** [comment]
Hi all.

I would say instead of "To make the transition as smooth as possible", we might want to say "You can only restore a backup of your Mail-in-a-Box to another machine running same version of Mail-in-a-Box that was installed when the backup was created. Since you'll be installing the latest version of Mail-in-a-Box on your new box, you must first make sure your current box is at the latest version. To do that".

But I agree that keeping the old box as it is and installing an _old_ version of Mail-in-a-Box on the new machine is probably a better practice. One can do that by setting the [TAG environment variable](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/bootstrap.sh#L9) to the version that's installed on the old box somewhere in the `curl|bash` install line. I'm ok merging this PR until we have better instructions.

(The best would be fixing Mail-in-a-Box so that this isn't necessary at all.)

**Comment by nikksno** [comment]
I actually think that there is no reason to install an old version, and that moving to a new box is just a good occasion to upgrade your current one, something you should already be doing anyway. If the user hasn't been keeping up to date, now is the time to do so, before upgrading. That's the way I see things, but I understand if you don't agree.

**Comment by nordurljosahvida** [comment]
Hi again, @JoshData what do you think of my latest comment? Do you see *any* reason why the user shouldn't want to take the opportunity to upgrade, especially since they would want to be doing so periodically anyway? Thanks

**Pull request closed without merging**
