### PR TITLE
Adding detail to guide on TLD to avoid

### PR DESCRIPTION
**Pull request by v60fan**
I've added reference links to the Discourse site and the registry to help people understand better why some domains don't work well with MIAB.

### CODE REVIEW

**Comment by v60fan** [comment]
I tested the HTML in rawgit to ensure the links worked, the css was consistent with the rest of the page, and the hyperlinks go to the right place.

**Comment by JoshData** [comment]
Hi,

I appreciate you pulling the info together. Can we do this in a way that doesn't list TLDs twice?

**Comment by v60fan** [comment]
Will try a different format to see if that suits. 

On 2016-05-07 16:10, Joshua Tauberer wrote:

> Hi, 
> 
> I appreciate you pulling the info together. Can we do this in a way that doesn't list TLDs twice? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/mail-in-a-box/mailinabox.email/pull/32#issuecomment-217643310

**Comment by v60fan** [comment]
Have tried a different format @JoshData . See if this suits, please.

**Comment by JoshData** [comment]
Thanks! Following-up with a slight tweak.

**Pull request merged**
